### ISSUE TITLE
Publish to Hex

### ISSUE THREAD

**Issue by zacksiri** [trbngr/Lyex#2]
We ran into the same issue, super glad we found your library we would love for this to be published to hex.pm any chance that can happen?

**Comment by trbngr** [comment]
Hi Zack,

There is no way I'm publishing this. haha.

It is broken for so many WSDLs, I can't in good faith do that. In fact I've pretty much given up on this project in favor just manually creating envelopes using `XmlBuilder` and reading responses with `SweetXml`.

I may in the future attempt a rewrite though.

**Comment by zacksiri** [comment]
Got it thx for the reply!
